package KieRule;
import com.drools.model.Order;

rule "HDFC rule discount"
 when
  orderObject : Order(cardType=="HDFC" && orderPrice>10000);
 then
  orderObject.setOrderDiscount(10);
 end;

rule "ICICI rule discount"
 when
  orderObject : Order(cardType=="ICICI" && orderPrice>15000);
 then
  orderObject.setOrderDiscount(8);
 end;

rule "DBS rule discount"
 when
  orderObject : Order(cardType=="DBS" && orderPrice>15000);
 then
  orderObject.setOrderDiscount(15);
 end;